- package.json
- src/App.tsx
- src/config.ts
- src/modules/editor/components/SlateEditor.tsx
- src/modules/editor/containers/Editor.tsx
- src/modules/editor/containers/SlateEditor.tsx
- src/modules/home/containers/Home.tsx
- src/modules/home/containers/StoryItem.tsx
- src/modules/layout/components/Login.tsx
- src/modules/layout/components/Protected.tsx
- src/modules/publicHome/components/PublicHome.tsx
- src/modules/publicStory/components/PublicStory.tsx
- src/react-app-env.d.ts
- src/utils/index.ts
- yarn.lock
- Update deps
- Hide the editor on mobile
- Editor toolbar is now sticky
- Show toasts on success and error
- Editor now support links
- Blockquote now working
- Better styling for the stories
- Special commands (pressing ctrl + b will set the text to bold etc ..)
> Improvements 1

- CHANGELOG.md
- src/modules/editor/components/StorySettings.tsx
- src/modules/editor/containers/StorySettings.tsx
> feat: delete cover image

- .github/workflows/nodejs.yml
- CHANGELOG.md
- src/modules/editor/components/SlateEditor.tsx
- src/modules/editor/components/StorySettings.tsx
- src/modules/editor/components/StorySettingsForm.tsx
- src/modules/home/components/StoryItem.tsx
- src/modules/home/containers/StoryItem.tsx
- src/modules/publicHome/components/PublicHome.tsx
- src/modules/publicHome/components/PublicStoryItem.tsx
- src/modules/publicStory/components/PublicStory.tsx
- src/types/index.ts
- src/utils/image.ts
- src/utils/index.ts
> feat: feature a story

- .eslintrc.js
- CHANGELOG.md
- package.json
- src/modules/editor/components/SlateEditor.tsx
- src/modules/editor/components/SlateEditorHoverMenu.tsx
- src/modules/editor/components/SlateEditorLink.tsx
- src/modules/editor/components/SlateEditorToolbar.tsx
- src/modules/editor/components/StorySettingsForm.tsx
- src/modules/editor/components/utils.ts
- src/modules/publicStory/components/PublicStory.tsx
- src/pages/_app.tsx
- yarn.lock
> feat: improve editor links

- src/modules/editor/components/StorySettingsForm.tsx
> feat: make cover image buttons more visible

- CHANGELOG.md
- package.json
- src/modules/publicStory/components/PublicStory.tsx
- src/pages-lib/[username]/[storyId].tsx
- yarn.lock
> feat: add reading time to the story page

- sigle/src/modules/editor/components/SlateEditor.tsx
> feat: save story before publishing

- blog-viewer/Dockerfile
- blog-viewer/src/modules/publicStory/PublicStory.tsx
- sigle/src/modules/publicStory/components/PublicStory.tsx
> fix: fix bold links not using the custom color

- .github/workflows/nodejs.yml
When the CI is running on a pull request, this test ensures that the docker build for Sigle is working properly.
> ci: test sigle docker build

- sigle/src/stitches.config.ts
- sigle/src/ui/Button.ts
> feat: sync orange design system

- sigle/src/modules/editor/BubbleMenu.tsx
Implement the right style for the bubble menu
> feat: editor bubble menu styling

- sigle/src/modules/publicHome/components/PublicHome.tsx
- sigle/src/modules/publicStory/components/PublicStory.tsx
Quick fix to restore the margins after the error page merge.
> fix: fix margin not working with full height page

- sigle/src/pages/_app.tsx
Use the new design system background color
> feat: new background color

- .changeset/late-cats-run.md
- .changeset/tricky-dragons-dress.md
- pnpm-lock.yaml
- sigle/package.json
- sigle/src/modules/editor/BubbleMenu.tsx
- sigle/src/modules/editor/TipTapEditor.tsx
> feat: add strikethrough and underline to editor

- sigle/src/modules/editor/NewEditor.tsx
- sigle/src/modules/editor/PublishDialog.tsx
- sigle/src/modules/editor/PublishedDialog.tsx
- sigle/src/modules/editor/StoryPublishedDialog.tsx
- sigle/src/modules/editor/TwitterCardPreview.tsx
- sigle/src/modules/editor/UnpublishDialog.tsx
- sigle/src/modules/editor/components/SlateEditor.tsx
- sigle/src/modules/editor/containers/SlateEditor.tsx
Allow stories to be published / unpublished in the new editor
Test cases:
1. on the current editor try to publish then unpublish to verify everything is still working correctly with the refactor
2. on the new editor try to publish then unpublish
> feat: new editor publish story

- .changeset/late-carrots-hear.md
- sigle/src/modules/editor/NewEditor.tsx
- sigle/src/modules/editor/containers/Editor.tsx
- sigle/src/modules/editor/utils/convertStateToHTML.tsx
- sigle/src/utils/migrations/story.ts
To test:
1. Write an article using the slate editor
2. save
3. add `?experimentalEditor=true` at the end of the url
4. Check that content is the same and was migrated successfully
> feat: migrate old content to new editor

- .changeset/rich-nails-judge.md
- packages/tailwind-style/dist/tailwind.css
- packages/tailwind-style/tailwind.config.js
- sigle/src/modules/editor/NewEditor.tsx
- sigle/src/modules/publicStory/components/PublicStory.tsx
Apply the new design system typography
> feat: mobile mode for typography content

- .changeset/curly-turtles-lie.md
- pnpm-lock.yaml
- sigle/package.json
- sigle/src/modules/editor/TipTapEditor.tsx
Displays a word count on the new editor. 
Closes #188
> feat: editor word count

- .changeset/hungry-berries-perform.md
- sigle/src/modules/editor/EditorHeader.tsx
After discussion with Quentin, we decided it would be good to add interactive styling to the back arrow on the editor header.
> refactor: update arrow styles

- sigle/src/modules/editor/FloatingMenu.tsx
- sigle/src/modules/editor/InlineMenu.tsx
- sigle/src/modules/editor/TipTapEditor.tsx
Use the correct path to upload images.
> feat: new editor better path images

- .changeset/silver-lions-fail.md
- sigle/src/modules/auth/AuthContext.tsx
- sigle/src/modules/editor/containers/SlateEditor.tsx
- sigle/src/modules/editor/utils/experimentalEditor.ts
- sigle/src/modules/home/containers/Home.tsx
- sigle/src/modules/layout/components/DashboardHeader.tsx
- sigle/src/modules/layout/components/DashboardLayout.tsx
- sigle/src/pages/index.tsx
- sigle/src/utils/featureFlags.ts
Create a feature flag to allow us to create the UI and test before the functionality is done. Can be used by adding `?experimentalHiroWallet=true`.
> feat: create hiro wallet feature flag

- sigle/src/pages/login.tsx
Closes : https://github.com/sigle/sigle/issues/365
If there is some other place outside of screenshot where I can see exactly which properties
of styles I had to use, I am happy to revisit and update to exact values. ( talking about $mt and $gray here ) 
This is how it will look after merging this and FF on!
> feat: new login setup

- .changeset/rude-shirts-walk.md
- sigle/src/modules/editor/InlineMenu.tsx
- sigle/src/modules/editor/TipTapEditor.tsx
Fix an issue when uploading large images/gifs in the editor and changing the focus before the upload is finished.
> fix: fix upload large images and focus

- .changeset/purple-knives-protect.md
- sigle/src/modules/layout/components/LoginLayout.tsx
- sigle/src/pages/login.tsx
- sigle/src/pages/register-username.tsx
This pr adds the following: 
- `register-username` page (without logic)
- Shared layout between the `login` and `register-username` pages
Closes #366
> feat: register username layout

- .changeset/clean-poets-itch.md
- sigle/src/modules/editor/EditorHeader.tsx
This pr adds functionality that allows the user to interact with the header when scrolling up, which allows them to view, save, publish, and access settings when writing long articles.
> feat: header visible on scroll up

- .changeset/light-waves-roll.md
- sigle/src/icons/FacebookLogoIcon.tsx
- sigle/src/icons/TwitterFilledIcon.tsx
- sigle/src/icons/index.tsx
- sigle/src/modules/publicStory/PublicStory.tsx
- sigle/src/modules/publicStory/ShareButtons.tsx
- sigle/src/stitches.config.ts
- sigle/src/ui/Tooltip.tsx
This pr adds functionality to allow users to share articles on social directly from the public story page.
Closes https://github.com/sigle/sigle/issues/54
> feat: add share buttons

- .changeset/poor-berries-search.md
- sigle/src/modules/publicStory/PublicStory.tsx
- sigle/src/modules/publicStory/ShareButtons.tsx
This pr fixes the issue of the author and url displaying incorrectly when sharing an article on social media.
> fix: share widgets

- .changeset/gold-jars-happen.md
- sigle/src/modules/home/components/StoryItem.tsx
- sigle/src/stitches.config.ts
- sigle/src/ui/DropdownMenu.ts
Updates the dropdown menu styles to be used in Story cards and new header. 
Closes #410
> feat: update dropdown menu styles

- .changeset/hot-donkeys-sleep.md
- sigle/src/modules/home/components/StoryItem.tsx
- sigle/src/stitches.config.ts
- sigle/src/ui/DropdownMenu.ts
Updates hover and active states to make interactions between dropdown items clearer for users with low-vision.
> feat: add clearer interactive states for dropdown

- .changeset/light-drinks-visit.md
- sigle/src/modules/layout/components/AppHeader.tsx
- sigle/src/ui/DropdownMenu.ts
Replaces hover card to now display a dropdown menu when clicking on username.
> feat: add dropdown header

- .changeset/stupid-shrimps-brush.md
- sigle/src/modules/publicHome/components/PublicHome.tsx
Adds a header to the blog pages.
Resolves #430
> feat: add header to blog page

- .changeset/sweet-ligers-do.md
- sigle/src/modules/home/components/StoryItem.tsx
- sigle/src/stitches.config.ts
- sigle/src/ui/Text.ts
This pr updates the story cards to the new redesign. 
Closes #412
> feat: redesign story cards

- .changeset/rich-icons-cross.md
- .changeset/three-lobsters-taste.md
- packages/tailwind-style/dist/tailwind.css
- packages/tailwind-style/tailwind.config.js
- sigle/src/components/Form.ts
- sigle/src/modules/editor/TwitterCardPreview.tsx
- sigle/src/modules/publicHome/components/PublicStoryItem.tsx
This pr fixes the following issues blocking dark mode release: 
- Text color on twitter preview cards displaying incorrectly
- Settings menu input text displaying incorrectly
- Editor links not updating when on dark mode
> fix: dark mode issues

- .changeset/eight-moles-agree.md
- sigle/src/modules/layout/components/AppHeader.tsx
- sigle/src/pages/_app.tsx
- sigle/src/pages/index.tsx
- sigle/src/utils/featureFlags.ts
> feat: enable dark theme

- .changeset/afraid-terms-sparkle.md
- sigle/src/external/fathom/__mocks__/index.ts
- sigle/src/external/fathom/aggregate.ts
- sigle/src/external/fathom/aggregateReferrers.ts
- sigle/src/external/fathom/index.ts
- sigle/src/pages/api/README.md
- sigle/src/pages/api/analytics/__snapshots__/referrers.test.ts.snap
- sigle/src/pages/api/analytics/referrers.api.ts
- sigle/src/pages/api/analytics/referrers.test.ts
Test url: http://localhost:3000/api/analytics/referrers?dateFrom=2022-01-01
> feat: stats referrer API

- .github/workflows/nextjs-bundle-analysis.yml
- sigle/package.json
Add https://github.com/hashicorp/nextjs-bundle-analysis
> chore: setup next.js bundle Analyses CI

- .changeset/dull-plums-invite.md
- sigle/src/modules/publicHome/components/PublicHome.tsx
- sigle/src/modules/settings/SettingsForm.tsx
- sigle/src/utils/index.ts
- sigle/src/utils/regex.ts
> fix: fix invalid website error

- .changeset/thick-starfishes-know.md
- sigle/src/modules/publicHome/components/PublicHome.tsx
> feat: custom SEO profile page

- .changeset/quick-trains-approve.md
- sigle/src/modules/analytics/stats/StatsFrame.tsx
Displays total views and visitors for given time period.
Closes #453
> feat: display total views and visitors

- .changeset/mighty-cooks-hang.md
- README.md
- sigle/src/modules/layout/components/LoginLayout.tsx
- sigle/src/pages/login.page.tsx
- sigle/src/ui/Typography.ts
- sigle/src/utils/featureFlags.tsx
> feat: new signing login flow, step 1

- .changeset/fair-melons-cry.md
- sigle/src/modules/analytics/ReferrersFrame.tsx
> fix: fix issue with referrer frame height

- .changeset/lemon-tips-press.md
- sigle/src/modules/home/components/Home.tsx
- sigle/src/modules/layout/components/AppHeader.tsx
- sigle/src/modules/layout/components/DashboardLayout.tsx
- sigle/src/ui/Accordion.tsx
- sigle/src/ui/Button.ts
> feat: move cta to sidebar and dropdown 

- sigle/src/hooks/subscriptions.ts
- sigle/src/modules/settings/plans/CurrentPlan.tsx
- sigle/src/modules/settings/plans/SelectNFTDialog.tsx
- sigle/src/pages/analytics/index.page.tsx
Move react-query calls to hooks so they can be reused
> chore: refactor hooks subscriptions

- .changeset/ten-bobcats-repeat.md
- sigle/src/modules/publicHome/components/PublicHome.tsx
This pr does the following:
- Fixes incorrect header width on profile page
- Refactors deprecated `Text` components to use new `Typography` components
- Replaces all styled components on the page with stitches
Closes #517
> fix: fix header width on profile page

- sigle/src/hooks/subscriptions.ts
- sigle/src/modules/settings/plans/ComparePlans.tsx
- sigle/src/modules/settings/plans/CurrentPlan.tsx
- sigle/src/modules/settings/plans/SelectNFTDialog.tsx
- users can now change the NFT from the current plan page
- users see the correct enabled plan for them on the compare plan page
> feat: allow user to change NFT from plan page

- .changeset/gorgeous-laws-pretend.md
- sigle/.env.test
- sigle/src/__mocks__/blockstack.ts
- sigle/src/jest.setup.ts
- sigle/src/modules/publicHome/components/PublicHome.tsx
- sigle/src/modules/publicStory/PublicStory.tsx
- sigle/src/pages/[username].page.tsx
- sigle/src/pages/[username].test.ts
- sigle/src/pages/[username]/[storyId].page.tsx
- sigle/src/pages/[username]/[storyId].test.tsx
With this pr, when doing ssr we now inject the user address so it can be used in the view.
> feat: return user stacks info for the user public pages

- .changeset/famous-windows-help.md
- sigle/src/modules/settings/SettingsForm.tsx
The image is now updating when you save but there's a slight moment where it shows the previous image when the value is reset. Is there a way to prevent this from happening? 
https://user-images.githubusercontent.com/65421744/176427681-d754f75c-ac91-4cca-b198-0b3996cf10ab.mov
> fix: fix image in settings not updating after saving

- .changeset/seven-shrimps-design.md
- sigle/src/modules/publicHome/components/PublicHome.tsx
- sigle/src/modules/storyCard/StoryCard.tsx
- sigle/src/modules/storyCard/StoryCardImage.tsx
- sigle/src/ui/IconButton.ts
* Adds **stories** tab to profile page
* Adds copyable stx address to bio
* Adds username tag next to display name
* Updates visual layout of writer info
Closes #566 #583
> feat: redesign profile

- .changeset/pink-days-shave.md
- sigle/src/modules/layout/components/AppHeader.tsx
- sigle/src/modules/storyCard/StoryCard.tsx
> feat: display custom usernames in header and on story cards

- sigle/src/ui/DropdownMenu.tsx
The background of the menu is transparent, update following the radix design system
> fix: fix dropdown menu transparent

- .changeset/curly-items-think.md
- pnpm-lock.yaml
- sigle/package.json
Try to fix hydratation missmatch on prod
> chore: upgrade next-themes to 0.2.0

- .changeset/five-dancers-float.md
- sigle/src/modules/publicHome/components/PublicHome.tsx
Adds an "Edit profile" button to the profile page.
Closes #411
> feat: add edit profile button to profile page

- .changeset/happy-meals-warn.md
- sigle/src/modules/layout/components/LoginLayout.tsx
- sigle/src/pages/configure-bns.page.tsx
- sigle/src/pages/login.page.tsx
- sigle/src/pages/register-username.page.tsx
Improves login flow by adding steps with progress indicators.
Closes #616
> feat: improve login flow

- .changeset/twelve-lemons-happen.md
- sigle/src/hooks/appData.ts
- sigle/src/modules/explore/Explore.tsx
- sigle/src/modules/profileCard/ProfileCard.tsx
- sigle/src/modules/publicHome/components/PublicHome.tsx
- sigle/src/modules/userCard/UserCard.tsx
Adds following and follower tabs to the profile page.
Closes #617
> feat: add following and follower tabs to profile page

- sigle/src/modules/publicHome/components/PublicHome.tsx
Fixes issue with user arriving at the incorrect tab when visiting another user profile from the follower/following tab list.
> fix: arriving at wrong tab when visiting another user profile

- .changeset/strong-years-report.md
- sigle/src/ui/Typography.ts
Update typography styles for upcoming mobile view tasks.
> feat: add typography styles for mobile

- .changeset/wet-rivers-smash.md
- sigle/src/modules/editor/NewEditor.tsx
- sigle/src/modules/editor/TipTapEditor.tsx
This pr updates the word count font size and the color of the title placeholder.
Closes #674
> feat: word count size

- .changeset/poor-cheetahs-matter.md
- sigle/src/modules/editor/TipTapEditor.tsx
- sigle/src/modules/editor/extensions/Placeholder/index.ts
This pr updates the editor placeholder text on mobile views. 
Closes #671
> feat: update placeholder on mobile

- .changeset/weak-carpets-appear.md
- sigle/src/modules/settings/plans/ComparePlans.tsx
- sigle/src/ui/Tooltip.tsx
- sigle/src/ui/Typography.ts
> feat: update tooltip styles

- .changeset/gentle-pumpkins-jump.md
- sigle/src/modules/editor/CoverImage.tsx
- sigle/src/modules/editor/EditorHeader.tsx
- sigle/src/modules/editor/EditorToolbar/EditorToolbar.tsx
> fix: fix cover image width on mobile

- .changeset/warm-news-grow.md
- sigle/src/modules/editor/TipTapEditor.tsx
- sigle/src/modules/editor/extensions/MobileScroll/index.ts
> fix: fix toolbar editor issue

- .changeset/wicked-feet-flow.md
- sigle/src/modules/layout/components/DashboardLayout.tsx
> feat: remove mobile accordion menu

- .changeset/wet-ravens-sleep.md
- sigle/src/modules/explore/Explore.tsx
- sigle/src/modules/feed/Feed.tsx
- sigle/src/modules/home/components/Home.tsx
> feat: add prompt if user has no content on feed page

- sigle/package.json
- sigle/src/modules/auth/sign-in-with-stacks/signInWithStacksMessage.ts
_fix for bytes to hex (excluding lockfile update)_
> fix: update bytes to hex

- .changeset/strange-wasps-beg.md
- sigle/src/modules/layout/components/DashboardLayout.tsx
- sigle/src/modules/publicHome/components/PublicHome.tsx
> feat: make profile page responsive

- .changeset/hot-olives-confess.md
- sigle/src/hooks/appData.ts
> fix: follow counters not updating

- .changeset/tasty-lamps-collect.md
- sigle/src/modules/userCard/UserCard.tsx
> feat: update user card styles

- .changeset/clever-rabbits-pump.md
- packages/sitemap-scripts/package.json
- pnpm-lock.yaml
- server/package.json
- server/prisma/migrations/20221021094132_added_stacks_username/migration.sql
- server/prisma/migrations/20221021094706_added_stacks_username/migration.sql
- server/prisma/schema.prisma
- server/src/analytics/analytics.service.ts
- server/src/stacks/stacks.service.spec.ts
- server/src/stacks/stacks.service.ts
- server/src/user/user.module.ts
- server/src/user/user.service.ts
- save stacks username and gaia info as well as block height
> feat: index stacks username and Gaia info

- .changeset/tough-cougars-speak.md
- sigle/src/modules/editor/EditorSettings/EditorSettings.tsx
- sigle/src/modules/publicStory/PublicStory.tsx
- sigle/src/types/index.ts
- sigle/src/ui/Form.ts
> feat: allow users to add a canonical link to a story

- .changeset/red-turkeys-peel.md
- sigle/src/modules/settings/plans/CurrentPlan.tsx
> feat: add message for legacy users on plans page

- .changeset/selfish-jobs-pump.md
- sigle/src/modules/analytics/Pagination.tsx
- sigle/src/modules/editor/CoverImage.tsx
- sigle/src/modules/editor/EditorHeader.tsx
- sigle/src/modules/editor/EditorSettings/EditorSettings.tsx
- sigle/src/modules/editor/FloatingMenu.tsx
- sigle/src/modules/editor/TipTapEditor.tsx
- sigle/src/modules/home/components/Home.tsx
- sigle/src/modules/home/components/StoryItem.tsx
- sigle/src/modules/layout/components/AppHeader.tsx
- sigle/src/modules/layout/components/DashboardLayout.tsx
- sigle/src/modules/profileCard/ProfileCard.tsx
- sigle/src/modules/publicHome/components/PublicHome.tsx
- sigle/src/modules/publicStory/ShareButtons.tsx
- sigle/src/modules/settings/SettingsForm.tsx
- sigle/src/modules/settings/plans/ComparePlans.tsx
- sigle/src/modules/settings/plans/CurrentPlan.tsx
- sigle/src/modules/settings/plans/SelectNFTDialog.tsx
- sigle/src/modules/userCard/UserCard.tsx
- sigle/src/stitches.config.ts
- sigle/src/ui/Button.ts
- sigle/src/ui/Dialog.tsx
- sigle/src/ui/IconButton.ts
- sigle/src/ui/Typography.ts
- Update normal button and icon button components with the new `md` variant
- Update all button instance size to `sm` to retain same sizing
Closes #746
> feat: update button variants

- .changeset/dull-actors-repeat.md
- sigle/src/modules/settings/SettingsForm.tsx
- sigle/src/modules/settings/SettingsLayout.tsx
- sigle/src/modules/settings/components/UnsavedChanges.tsx
- sigle/src/modules/settings/newsletter/Newsletter.tsx
- sigle/src/modules/settings/private-data/PrivateData.tsx
- sigle/src/pages/settings/newsletter.page.tsx
- sigle/src/pages/settings/private-data.page.tsx
- sigle/src/types/index.ts
- sigle/src/ui/Form.ts
- sigle/src/utils/featureFlags.tsx
- sigle/src/utils/regex.ts
> feat: add settings tabs

- .changeset/thin-apples-call.md
- sigle-next/src/pages/_app.page.tsx
- sigle-next/src/pages/_document.page.tsx
- sigle-next/src/styles/tailwind.ts
Fix rendering issues with css order
> chore: use tailwind reset as js object

- .changeset/cool-guests-flow.md
- apps/sigle-next/src/components/StoryCard/StoryCardDraft.tsx
Closes https://github.com/sigle/sigle/issues/871
> feat: "No Title" placeholder on Story cards

- .changeset/six-drinks-care.md
- apps/custom-domain/src/sites.ts
- apps/custom-domain/tailwind.config.js
Closes https://github.com/sigle/sigle/issues/894
> fix: fix images not centered

- .github/workflows/nodejs.yml
- CONTRIBUTING.md
- pnpm-lock.yaml
- sigle/Dockerfile.e2e
- sigle/package.json
- sigle/src/pages/login.page.tsx
- properly report e2e failing tests
- upgrade playwright
> chore: failing e2e tests

- apps/custom-domain/eslint.config.mjs
- apps/custom-domain/package.json
- apps/custom-domain/src/components/Post/TableOfContents.tsx
- apps/custom-domain/src/components/Shared/Post/Card/index.tsx
- apps/custom-domain/src/components/ui/Sheet.tsx
- apps/sigle/eslint.config.mjs
- apps/sigle/package.json
- apps/sigle/src/app/(dashboard)/dashboard/layout.tsx
- apps/sigle/src/components/Editor/BottomInfo/index.tsx
- apps/sigle/src/components/Editor/EditorTiptap.tsx
- apps/sigle/src/components/User/ProfileHeader.tsx
- pnpm-lock.yaml
switch to get tailwind 4 css ready
> chore: eslint-plugin-better-tailwindcss
