sigle/sigle

CHANGELOG.md, src/modules/editor/components/SlateEditor.tsx, src/modules/editor/components/SlateEditorHoverMenu.tsx, src/modules/editor/components/SlateEditorToolbar.tsx, src/modules/publicStory/components/PublicStory.tsx
**Inline code blocks**: In the editor you can now find the "code" option to style your text. This is a first step before we get fully highlighted code blocks.
Related to #26
=> feat: add inline code marks

sigle/package.json, sigle/src/modules/editor/components/SlateEditor.tsx, yarn.lock
Change is required for tip tap, in any case, it's good to upgrade this major that we use only once 😅
=> chore: upgrade tippyjs/react to v4

sigle/package.json, sigle/src/pages/_app.tsx, yarn.lock
=> chore: upgrade react-toastify to v8

sigle/next-env.d.ts, sigle/src/pages/_app.tsx, sigle/src/pages/_middleware.ts
When I wrote this logic middlewares were not a thing in next.js, now we can handle properly the HTTPS redirection server-side.
The middleware is run at the edge with the fly firecracker.
=> feat: use next middleware to redirect to HTTPS

sigle/src/icons/RoundPlus.tsx, sigle/src/icons/index.tsx, sigle/src/modules/editor/FloatingMenu.tsx, sigle/src/modules/editor/TipTapEditor.tsx
Create an inline menu displayed on the left side when you create a new empty paragraph. Clicking on the + icon should open the slash menu.
=> feat: inline menu open slash command

sigle/src/modules/editor/BubbleMenu.tsx
With this change, a user can type a link with the keyboard only and the selection is properly handled.
=> feat: editor improve link handling

sigle/src/modules/editor/components/SlateEditor.tsx, sigle/src/modules/editor/components/SlateEditorSideMenu.tsx, sigle/src/modules/editor/components/SlateEditorToolbar.tsx
Add GIF support to the current slate Editor. Will be migrated to the new TipTap editor too once I add support of images there.
Fixes https://github.com/pradel/sigle/issues/109
=> feat: add GIF support to editor

.changeset/afraid-worms-own.md, sigle/src/pages/_document.tsx
With this, we force stitches to be rendered last so we know the reset CSS defaults will not overwrite the stitches css
=> fix: stitches injection order

.changeset/metal-oranges-trade.md, sigle/src/modules/editor/CoverImage.tsx, sigle/src/modules/editor/NewEditor.tsx, sigle/src/modules/editor/TipTapEditor.tsx, sigle/src/ui/IconButton.ts
You can now edit on the editor page directly the cover image (not in the settings). Only available on the new editor.
=> feat: improve cover image behavior new editor

.changeset/smart-lies-complain.md, sigle/src/modules/editor/TipTapEditor.tsx
This pr fixes the word count being shown on a published story page.
Fixes #346
=> fix: word count showing on published story

.changeset/lovely-knives-tie.md, sigle/src/modules/publicStory/components/PoweredBy.tsx
This pr migrates the styling of `Powered By` section from styled components to stitches.
Closes https://github.com/sigle/sigle/issues/348
=> refactor: migrate PoweredBy styles from styled components to stitches

.changeset/fair-falcons-kiss.md
Let's mark the current version as 1.0.0 and follow consistent versioning from now on.
=> chore: create first major release

.changeset/eighty-ghosts-care.md, .changeset/proud-tigers-fail.md, packages/tailwind-style/dist/tailwind.css, packages/tailwind-style/tailwind.config.js, sigle/src/modules/publicStory/PublicStory.tsx, sigle/src/modules/publicStory/ShareButtons.tsx
This pr fixes the issue of underlined links outside of the article itself (Date, share icons). 
Questions/Concerns: 
- As Quentin mentioned, links are still underlined in the editor so if a user wants to manually underline using `Ctrl/Cmd + U` 2 underlines will appear. Do you have any ideas on how best to approach resolving this @pradel ?
Closes #426
=> fix: underlined links outside of article

.changeset/tall-bats-retire.md, sigle/src/modules/layout/components/AppHeader.tsx
This pr updates the dropdown (header) trigger to prefer using a button over the `Flex` element.
=> feat: use button for dropdown trigger

.changeset/long-elephants-wink.md, sigle/src/components/Form.ts, sigle/src/ui/Dialog.tsx
=> fix: dialog and settings text color on dark mode

.changeset/spotty-countries-fry.md, sigle/src/modules/editor/EditorHeader.tsx
Given the fact users are unable to scroll when the overlay is active, adding some logic to enable the needed `position: sticky` and `zIndex: 1` properties only when the scroll position is at a certain height seems solve the issue. 
Will raise the issue to the Radix team anyway 👍
Closes #440
=> fix: editor header showing over settings modal

.changeset/sixty-dragons-attack.md, sigle/src/modules/editor/EditorHeader.tsx, sigle/src/pages/_app.tsx, sigle/src/ui/Dialog.tsx
Although the previous fix took care of the header appearing over settings at the top of the page, once further down the page and trying to access the settings, the bug remained like so:
After some digging, I came across [this](https://discord.com/channels/752614004387610674/803656530259738674/918963737610838078) from the Radix help discord channel - so following the advice given there to set a new stacking context at root in conjunction with the Dialog Portal has now solved the issue :)
=> fix: dialog portal issue

.changeset/selfish-bananas-lie.md, sigle/src/modules/analytics/ReferrersFrame.tsx, sigle/src/modules/analytics/components/Analytics.tsx, sigle/src/modules/layout/components/DashboardLayout.tsx
Adds referrers with dummy data to the analytics page. 
Enable analytics page by adding `?experimentalAnalyticsPage=true` at the end of the root URL.
Closes #451
=> feat: analytics referrers

sigle/src/hooks/analytics.ts, sigle/src/modules/analytics/PublishedStoriesFrame.tsx, sigle/src/modules/analytics/PublishedStoryItem.tsx, sigle/src/modules/analytics/ReferrersFrame.tsx, sigle/src/modules/analytics/components/Analytics.tsx, sigle/src/modules/analytics/components/StoryItemAnalytics.tsx, sigle/src/modules/analytics/containers/StoryItemAnalytics.tsx, sigle/src/modules/analytics/stats/StatsFrame.tsx, sigle/src/pages/_app.page.tsx
=> chore: refactor analytics and fix some issues

.changeset/dirty-pots-battle.md, sigle/src/modules/settings/plans/ComparePlans.tsx
This pr updates the delay duration for the tooltip on the "Compare plans" page. 
Fixes #570
=> fix: make tooltip delay duration more instant

.changeset/brown-schools-pay.md, server/prisma/migrations/20220718165354_added_user_legacy/migration.sql, server/prisma/schema.prisma, server/src/api/modules/users/[userId].ts
Right now we just save to the DB users that signed a message, we should also save the legacy users so the relations are not broken in the DB
=> feat: index legacy users

sigle/src/modules/profileCard/ProfileCard.tsx
Right now every time you open the card, requests are made to fetch the latest data to the server, even tho the data didn't change. With this change, the data is fetched once the card is opened and then the cache is used when it's reopened.
=> feat: optimise hover card data fetching

.changeset/cold-balloons-camp.md, sigle/src/modules/layout/components/DashboardLayout.tsx
Fixes issue where profile tab is not navigating to profile page as there is a missing `as` prop for the dynamic route.
=> fix: profile tab not navigating to profile page

.changeset/quick-birds-tease.md, sigle/src/modules/editor/EditorHeader.tsx
Updates the editor header to be responsive for mobile. Fonts will be correct size when [this pr](https://github.com/sigle/sigle/pull/641) is merged. 
Closes #636
=> feat: make editor header responsive

.changeset/shy-pans-vanish.md, sigle/src/modules/editor/TipTapEditor.tsx, sigle/src/modules/editor/extensions/Placeholder/index.ts
The goal of this pr is to improve the placeholder text based on the block types, this will give more context to the writer.
List of changes:
- when selecting big heading => "Big Heading" placeholder is shown
- when selecting small heading => "Small Heading" placeholder is shown
- fixed an issue for first text when editor is empty
- all lists items => "List" placeholder
- empty quote => "Quote" placeholder
- when quote has more than 2 child => "Type or hit enter to exit quote" placeholder
Example for the quote:
=> feat: improve editor placeholder behavior

.changeset/hip-islands-sin.md, sigle/src/modules/layout/components/AppHeader.tsx
=> fix: mobile header logo not navigating

.changeset/many-boats-argue.md, sigle/src/modules/editor/CoverImage.tsx, sigle/src/ui/Button.ts, sigle/src/ui/ErrorMessage.tsx
- Improves user experience when dragging and dropping an image on the cover image trigger.
Closes #654
=> feat: cover image drop

.changeset/hot-wombats-peel.md, sigle/src/modules/editor/TipTapEditor.tsx
This pr fixes the issue with missing box shadow for floating menu on light mode.
=> fix: no box shadow on floating menu

.changeset/thin-needles-camp.md, sigle/src/modules/publicHome/components/PublicHome.tsx
- Adds boring avatar fallback if the user has no profile image
- Encodes image url 
Tool used to verify og meta image is working: https://www.opengraph.xyz/
Closes #684
=> feat: add fallback og image when sharing profile page

.changeset/kind-impalas-hammer.md, sigle/src/modules/storyCard/StoryCardImage.tsx
The story "Cycle #46" is missing the cover image. https://app.sigle.io/friedgerpool.btc
=> fix: fix cover image not showing in list
